;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		beginning-of-visual-line
		c-electric-semi&comma
		end-of-visual-line
		eval-and-replace
		eval-last-sexp
		fix-word-capitalize
		hungry-delete-backward
		hungry-delete-forward
		indent-for-tab-command
		kill-region
		kill-visual-line
		org-beginning-of-line
		org-end-of-line
		org-promote-subtree
		org-return
		org-self-insert-command
		org-yank
		))

(setq mc/cmds-to-run-once
      '(
		ace-window
		handle-select-window
		helm-M-x
		ignore
		mouse-set-region
		multiple-cursors-hydra/body
		multiple-cursors-hydra/ignore
		multiple-cursors-hydra/mc/add-cursor-on-click
		multiple-cursors-hydra/mc/edit-lines-and-exit
		multiple-cursors-hydra/mc/mark-all-like-this-and-exit
		multiple-cursors-hydra/mc/mark-next-like-this
		multiple-cursors-hydra/mc/mark-previous-like-this
		multiple-cursors-hydra/mc/unmark-next-like-this
		multiple-cursors-hydra/mc/unmark-previous-like-this
		multiple-cursors-hydra/nil
		org-cycle
		org-shifttab
		text-scale-adjust
		))
